/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cronometro;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


public class FrmCronometro extends javax.swing.JFrame {
    int contador=0;
    int decimas=0;
    int segundos=0;
    int minutos=0;
    int aciertos=0;
    int total=0;
    int reset=0;
    Timer temporizador = new Timer(100, new ActionListener()
    {
            public void actionPerformed(ActionEvent e)
            {
                contador+=1;
                lbldecimas.setText(String.valueOf(contador));
                decimas+=1;
                if(decimas==10)
                {
                    segundos +=1;
                    decimas=0;
                }
                if (segundos == 60)
                {
                    minutos +=1;
                    segundos=0;
                }
                lbldecimas.setText(String.valueOf(decimas));
                lblsegundero.setText(String.valueOf(segundos));
                lblminutero.setText(String.valueOf(minutos));
                
                if (segundos<=9)
                {
                    lblsegundero.setText("0" + String.valueOf(segundos));
                }
                
                
            }
        });
    public FrmCronometro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        btmstart = new javax.swing.JButton();
        btmstop = new javax.swing.JButton();
        lblminutero = new javax.swing.JLabel();
        btmreset = new javax.swing.JButton();
        lblaciertos = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblsegundero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbldecimas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmstart.setText("Start");
        btmstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmstartActionPerformed(evt);
            }
        });

        btmstop.setText("Stop");
        btmstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmstopActionPerformed(evt);
            }
        });

        lblminutero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblminutero.setForeground(new java.awt.Color(255, 0, 0));
        lblminutero.setText("0");

        btmreset.setText("Reset");
        btmreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmresetActionPerformed(evt);
            }
        });

        lblaciertos.setText("0");

        lbltotal.setText("0");

        jLabel4.setText(":");

        lblsegundero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblsegundero.setForeground(new java.awt.Color(255, 51, 0));
        lblsegundero.setText("00");

        jLabel7.setText(":");

        lbldecimas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldecimas.setForeground(new java.awt.Color(255, 51, 51));
        lbldecimas.setText("0");

        jLabel9.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmreset, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmstop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmstart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblaciertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblminutero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsegundero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldecimas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btmstart)
                            .addComponent(lblaciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmstop)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmreset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblminutero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblsegundero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbldecimas))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmstartActionPerformed
        temporizador.start();
    }//GEN-LAST:event_btmstartActionPerformed

    private void btmstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmstopActionPerformed
        temporizador.stop();
        total+=1;
        if (decimas==0)
        {
            aciertos+=1;
        }
        lblaciertos.setText(String.valueOf(aciertos));
        lbltotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btmstopActionPerformed

    private void btmresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmresetActionPerformed
        aciertos=0;
        total=0;
        segundos=0;
        minutos=0;
        decimas=0;
        
        lblaciertos.setText(String.valueOf(aciertos));
        lbltotal.setText(String.valueOf(total));
        lbldecimas.setText(String.valueOf(decimas));
        lblsegundero.setText(String.valueOf(segundos));
        lblminutero.setText(String.valueOf(minutos));
    }//GEN-LAST:event_btmresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmreset;
    private javax.swing.JButton btmstart;
    private javax.swing.JButton btmstop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblaciertos;
    private javax.swing.JLabel lbldecimas;
    private javax.swing.JLabel lblminutero;
    private javax.swing.JLabel lblsegundero;
    private javax.swing.JLabel lbltotal;
    // End of variables declaration//GEN-END:variables
}
